version: "3.4"

services:
  build:
    image: golang:1.16
    command: ["bash", "-c", "cd /app/example && go build main.go"]
    volumes:
      - .:/app

  example:
    image: pgbroker-example:latest
    build:
      context: .
      dockerfile: Dockerfile.example
    depends_on:
      - postgres
    volumes:
      - .:/pprof

  postgres:
    image: postgres:11-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  pgbench:
    image: postgres:11-alpine
    command: ["bash", "-c", "
      sleep 5 && \
      pgbench -i -s 5 -h example -U postgres && \
      echo && \
      pgbench -T 10 -M simple -h example -U postgres && \
      echo && \
      pgbench -T 10 -M extended -h example -U postgres && \
      echo && \
      pgbench -T 10 -M prepared -h example -U postgres
    "]
    depends_on:
      - example